GET http://localhost:3003/api/projects/69affbadf414d4d39555b527
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoib2dvb2x1d2EiLCJlbWFpbCI6ImJhZGFydW51cmF0dWxsYWhvQGdtYWlsLmNvbSIsInZlcmlmaWVkIjp0cnVlLCJwcm9qZWN0cyI6W10sInBhcnRpY2lwYXRpbmdQcm9qZWN0cyI6W10sImlkIjoiNjlhZmZhZGRmNDE0ZDRkMzk1NTViNTIxIn0sImlhdCI6MTc3MzE0MDgyOCwiZXhwIjoxNzczMjI3MjI4fQ.1g7h4hZW-p5MFumvm7_srFkORsPQW53Xr0oY6Qqe5Ok